# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_scc_v2_organization_mute_config'
generation_type: 'mmv1'
source_file: 'products/securitycenterv2/OrganizationMuteConfig.yaml'
api_service_name: 'securitycenter.googleapis.com'
api_version: 'v2'
api_resource_type_kind: 'MuteConfig'
api_variant_patterns:
  - 'organizations/{organization}/locations/{location}/muteConfigs/{muteConfig}'
fields:
  - field: 'create_time'
  - field: 'description'
  - field: 'filter'
  - field: 'location'
    provider_only: true
  - field: 'most_recent_editor'
  - field: 'mute_config_id'
    provider_only: true
  - field: 'name'
  - field: 'organization'
    provider_only: true
  - field: 'type'
  - field: 'update_time'
