# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_scc_v2_folder_notification_config'
generation_type: 'mmv1'
source_file: 'products/securitycenterv2/FolderNotificationConfig.yaml'
api_service_name: 'securitycenter.googleapis.com'
api_version: 'v2'
api_resource_type_kind: 'NotificationConfig'
api_variant_patterns:
  - 'folders/{folder}/locations/{location}/notificationConfigs/{notificationConfig}'
fields:
  - field: 'config_id'
    provider_only: true
  - field: 'description'
  - field: 'folder'
    provider_only: true
  - field: 'location'
    provider_only: true
  - field: 'name'
  - field: 'pubsub_topic'
  - field: 'service_account'
  - field: 'streaming_config.filter'
