# Copyright IBM Corp. 2014, 2026
# SPDX-License-Identifier: MPL-2.0
resource: google_scc_v2_organization_notification_config
generation_type: mmv1
source_file: products/securitycenterv2/OrganizationNotificationConfig.yaml
api_service_name: securitycenter.googleapis.com
api_version: v2
api_resource_type_kind: NotificationConfig
cai_asset_name_formats:
    - //securitycenter.googleapis.com/organizations/{{organization}}/locations/{{location}}/notificationConfigs/{{config_id}}
api_variant_patterns:
    - organizations/{organization}/locations/{location}/notificationConfigs/{notificationConfig}
fields:
    - field: config_id
      provider_only: true
    - api_field: description
    - field: location
      provider_only: true
    - api_field: name
    - field: organization
      provider_only: true
    - api_field: pubsubTopic
    - api_field: serviceAccount
    - api_field: streamingConfig.filter
