resource: 'google_kms_autokey_config'
generation_type: 'mmv1'
source_file: 'products/kms/AutokeyConfig.yaml'
api_service_name: 'cloudkms.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'AutokeyConfig'
fields:
  - field: 'etag'
  - field: 'folder'
    provider_only: true
  - field: 'key_project'
