// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/apigee/TargetServer.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/samples/base_configs/query_test_file.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package apigee_test

import (
	"strings"
	"testing"
	"time"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/querycheck"
	"github.com/hashicorp/terraform-plugin-testing/querycheck/queryfilter"
	"github.com/hashicorp/terraform-plugin-testing/tfversion"

	"github.com/hashicorp/terraform-provider-google/google/acctest"
	"github.com/hashicorp/terraform-provider-google/google/envvar"
	_ "github.com/hashicorp/terraform-provider-google/google/services/apigee"
	_ "github.com/hashicorp/terraform-provider-google/google/services/compute"
	_ "github.com/hashicorp/terraform-provider-google/google/services/resourcemanager"
	_ "github.com/hashicorp/terraform-provider-google/google/services/servicenetworking"
)

var (
	_ = strings.Trim
	_ = envvar.TestEnvVar
	_ = time.Now
)

func TestAccApigeeTargetServerListQuery_generated(t *testing.T) {

	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)
	context := map[string]interface{}{
		"billing_account": envvar.GetTestBillingAccountFromEnv(t),
		"org_id":          envvar.GetTestOrgFromEnv(t),
		"random_suffix":   randomSuffix,
	}

	var listDisplayName acctest.ListDisplayName
	var listScope acctest.ListScopeCapture
	acctest.VcrTest(t, resource.TestCase{
		TerraformVersionChecks: []tfversion.TerraformVersionCheck{
			tfversion.SkipBelow(tfversion.Version1_14_0),
		},
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		ExternalProviders: map[string]resource.ExternalProvider{
			"time": {},
		},
		CheckDestroy: testAccCheckApigeeTargetServerDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccApigeeTargetServer_apigeeTargetServerTestExample(context),
				Check: resource.ComposeTestCheckFunc(
					listDisplayName.Capture(
						"google_apigee_target_server.apigee_target_server",
						[]string{
							"name",
						},
					),
					listScope.Capture(map[string]string{
						"env_id": "google_apigee_target_server.apigee_target_server",
					}),
				),
			},
			{
				Query:           true,
				Config:          testAccApigeeTargetServer_apigeeTargetServerTestExampleListQuery(context),
				ConfigVariables: listScope.AsConfigVariables(),
				QueryResultChecks: []querycheck.QueryResultCheck{
					querycheck.ExpectLengthAtLeast("google_apigee_target_server.list_query", 1),
					querycheck.ExpectResourceDisplayName(
						"google_apigee_target_server.list_query",
						queryfilter.ByDisplayName(listDisplayName.CheckValue()),
						listDisplayName.CheckValue(),
					),
				},
			},
		},
	})
}

func testAccApigeeTargetServer_apigeeTargetServerTestExampleListQuery(context map[string]interface{}) string {
	return acctest.Nprintf(`
variable "env_id" { type = string }
list "google_apigee_target_server" "list_query" {
    provider = google
	limit = 10000
    config {
        env_id = var.env_id
    }
}
`, context)
}
