# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_apigee_addons_config'
generation_type: 'mmv1'
source_file: 'products/apigee/AddonsConfig.yaml'
api_service_name: 'apigee.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'AddonsConfig'
fields:
  - field: 'addons_config.advanced_api_ops_config.enabled'
  - field: 'addons_config.api_security_config.enabled'
  - field: 'addons_config.api_security_config.expires_at'
  - field: 'addons_config.connectors_platform_config.enabled'
  - field: 'addons_config.connectors_platform_config.expires_at'
  - field: 'addons_config.integration_config.enabled'
  - field: 'addons_config.monetization_config.enabled'
  - field: 'org'
    provider_only: true
