resource: 'google_apigee_addons_config'
generation_type: 'mmv1'
source_file: 'products/apigee/AddonsConfig.yaml'
api_service_name: 'apigee.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'AddonsConfig'
fields:
  - api_field: 'addonsConfig.advancedApiOpsConfig.enabled'
  - api_field: 'addonsConfig.apiSecurityConfig.enabled'
  - api_field: 'addonsConfig.apiSecurityConfig.expiresAt'
  - api_field: 'addonsConfig.connectorsPlatformConfig.enabled'
  - api_field: 'addonsConfig.connectorsPlatformConfig.expiresAt'
  - api_field: 'addonsConfig.integrationConfig.enabled'
  - api_field: 'addonsConfig.monetizationConfig.enabled'
  - field: 'org'
    provider_only: true
