resource: 'google_apigee_environment'
generation_type: 'mmv1'
source_file: 'products/apigee/Environment.yaml'
api_service_name: 'apigee.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'Environment'
fields:
  - field: 'api_proxy_type'
  - field: 'deployment_type'
  - field: 'description'
  - field: 'display_name'
  - field: 'forward_proxy_uri'
  - field: 'name'
  - field: 'node_config.current_aggregate_node_count'
  - field: 'node_config.max_node_count'
  - field: 'node_config.min_node_count'
  - field: 'org_id'
    provider_only: true
  - field: 'properties.property.name'
  - field: 'properties.property.value'
  - field: 'type'
