# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

groups:
  - name: devs
    reviewers: 1
    usernames:
      - rileykarson
      - slevenick
      - c2thorn
      - scottsuarez
      - melinath
      - megan07
      - shuyama1
