run:
  deadline: 2m30s

issues:
  exclude-rules:
    # Exclude issues from staticcheck. staticcheck.conf doesn't seem to work.
    - linters:
        - staticcheck
      text: "S1021:"

    - linters:
        - staticcheck
      text: "SA1019:"

    - linters:
        - staticcheck
      text: "SA4006:"

    - linters:
        - staticcheck
      text: "SA4023"

    - linters:
        - staticcheck
      text: "SA6005:"

  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gofmt
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - unconvert
    - unused
    - varcheck
    - vet

linters-settings:
  errcheck:
    ignore: github.com/hashicorp/terraform-plugin-sdk/helper/schema:ForceNew|Set,fmt:.*,io:Close,github.com/hashicorp/terraform-provider-google/google:Set
