dist: trusty
sudo: required
services:
- docker
language: go
go:
- "1.11"

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh
- go get github.com/kardianos/govendor

script:
- make test
- make vendor-status
- make vet
- make website-test

branches:
  only:
  - master
  - 2.0.0
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
