resource: 'google_os_config_v2_policy_orchestrator_for_organization'
generation_type: 'mmv1'
source_file: 'products/osconfigv2/PolicyOrchestratorForOrganization.yaml'
api_service_name: 'osconfig.googleapis.com'
api_version: 'v2'
api_resource_type_kind: 'PolicyOrchestrator'
api_variant_patterns:
  - 'organizations/{organization}/locations/{location}/policyOrchestrators/{policyOrchestrator}'
autogen_status: true
fields:
  - field: 'action'
  - field: 'create_time'
  - field: 'description'
  - field: 'effective_labels'
    provider_only: true
  - field: 'etag'
  - field: 'labels'
  - field: 'name'
  - field: 'orchestrated_resource.id'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.baseline'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.deleted'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.description'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.etag'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.instance_filter.all'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.instance_filter.exclusion_labels.labels'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.instance_filter.inclusion_labels.labels'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.instance_filter.inventories.os_short_name'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.instance_filter.inventories.os_version'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.name'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.allow_no_resource_group_match'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.description'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.id'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.mode'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.inventory_filters.os_short_name'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.inventory_filters.os_version'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.exec.enforce.args'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.exec.enforce.file.allow_insecure'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.exec.enforce.file.gcs.bucket'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.exec.enforce.file.gcs.generation'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.exec.enforce.file.gcs.object'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.exec.enforce.file.local_path'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.exec.enforce.file.remote.sha256_checksum'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.exec.enforce.file.remote.uri'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.exec.enforce.interpreter'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.exec.enforce.output_file_path'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.exec.enforce.script'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.exec.validate.args'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.exec.validate.file.allow_insecure'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.exec.validate.file.gcs.bucket'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.exec.validate.file.gcs.generation'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.exec.validate.file.gcs.object'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.exec.validate.file.local_path'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.exec.validate.file.remote.sha256_checksum'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.exec.validate.file.remote.uri'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.exec.validate.interpreter'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.exec.validate.output_file_path'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.exec.validate.script'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.file.content'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.file.file.allow_insecure'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.file.file.gcs.bucket'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.file.file.gcs.generation'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.file.file.gcs.object'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.file.file.local_path'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.file.file.remote.sha256_checksum'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.file.file.remote.uri'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.file.path'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.file.permissions'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.file.state'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.id'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.apt.name'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.deb.pull_deps'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.deb.source.allow_insecure'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.deb.source.gcs.bucket'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.deb.source.gcs.generation'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.deb.source.gcs.object'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.deb.source.local_path'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.deb.source.remote.sha256_checksum'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.deb.source.remote.uri'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.desired_state'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.googet.name'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.msi.properties'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.msi.source.allow_insecure'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.msi.source.gcs.bucket'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.msi.source.gcs.generation'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.msi.source.gcs.object'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.msi.source.local_path'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.msi.source.remote.sha256_checksum'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.msi.source.remote.uri'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.rpm.pull_deps'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.rpm.source.allow_insecure'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.rpm.source.gcs.bucket'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.rpm.source.gcs.generation'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.rpm.source.gcs.object'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.rpm.source.local_path'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.rpm.source.remote.sha256_checksum'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.rpm.source.remote.uri'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.yum.name'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.pkg.zypper.name'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.repository.apt.archive_type'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.repository.apt.components'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.repository.apt.distribution'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.repository.apt.gpg_key'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.repository.apt.uri'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.repository.goo.name'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.repository.goo.url'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.repository.yum.base_url'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.repository.yum.display_name'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.repository.yum.gpg_keys'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.repository.yum.id'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.repository.zypper.base_url'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.repository.zypper.display_name'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.repository.zypper.gpg_keys'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.os_policies.resource_groups.resources.repository.zypper.id'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.reconciling'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.revision_create_time'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.revision_id'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.rollout.disruption_budget.fixed'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.rollout.disruption_budget.percent'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.rollout.min_wait_duration'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.rollout_state'
  - field: 'orchestrated_resource.os_policy_assignment_v1_payload.uid'
  - field: 'orchestration_scope.selectors.location_selector.included_locations'
  - field: 'orchestration_scope.selectors.resource_hierarchy_selector.included_folders'
  - field: 'orchestration_scope.selectors.resource_hierarchy_selector.included_projects'
  - field: 'orchestration_state.current_iteration_state.error.code'
  - field: 'orchestration_state.current_iteration_state.error.details.type_url'
  - field: 'orchestration_state.current_iteration_state.error.details.value'
  - field: 'orchestration_state.current_iteration_state.error.message'
  - field: 'orchestration_state.current_iteration_state.failed_actions'
  - field: 'orchestration_state.current_iteration_state.finish_time'
  - field: 'orchestration_state.current_iteration_state.performed_actions'
  - field: 'orchestration_state.current_iteration_state.progress'
  - field: 'orchestration_state.current_iteration_state.rollout_resource'
  - field: 'orchestration_state.current_iteration_state.start_time'
  - field: 'orchestration_state.current_iteration_state.state'
  - field: 'orchestration_state.previous_iteration_state.error.code'
  - field: 'orchestration_state.previous_iteration_state.error.details.type_url'
  - field: 'orchestration_state.previous_iteration_state.error.details.value'
  - field: 'orchestration_state.previous_iteration_state.error.message'
  - field: 'orchestration_state.previous_iteration_state.failed_actions'
  - field: 'orchestration_state.previous_iteration_state.finish_time'
  - field: 'orchestration_state.previous_iteration_state.performed_actions'
  - field: 'orchestration_state.previous_iteration_state.progress'
  - field: 'orchestration_state.previous_iteration_state.rollout_resource'
  - field: 'orchestration_state.previous_iteration_state.start_time'
  - field: 'orchestration_state.previous_iteration_state.state'
  - field: 'organization_id'
    provider_only: true
  - field: 'policy_orchestrator_id'
    provider_only: true
  - field: 'reconciling'
  - field: 'state'
  - field: 'terraform_labels'
    provider_only: true
  - field: 'update_time'
