// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

// Package cloudrun contains resources, datasources, etc. for the cloud run service.
package cloudrun

import (
	"github.com/hashicorp/terraform-provider-google/google/registry"
)

var Product = registry.Product{
	Name:                 "cloudrun",
	BaseUrl:              "https://{{location}}-run.googleapis.com/",
	CustomEndpointField:  "cloud_run_custom_endpoint",
	CustomEndpointEnvVar: "GOOGLE_CLOUD_RUN_CUSTOM_ENDPOINT",
}

func init() {
	Product.Register()
}
