// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

// Package servicemanagement contains resources, datasources, etc. for the cloud endpoints service.
package servicemanagement

import (
	"github.com/hashicorp/terraform-provider-google/google/registry"
)

var Product = registry.Product{
	Name:                 "servicemanagement",
	BaseUrl:              "https://servicemanagement.googleapis.com/v1/",
	CustomEndpointField:  "service_management_custom_endpoint",
	CustomEndpointEnvVar: "GOOGLE_SERVICE_MANAGEMENT_CUSTOM_ENDPOINT",
}

func init() {
	Product.Register()
}
