# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_eventarc_google_channel_config'
generation_type: 'mmv1'
source_file: 'products/eventarc/GoogleChannelConfig.yaml'
api_service_name: 'eventarc.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'GoogleChannelConfig'
fields:
  - field: 'crypto_key_name'
  - field: 'location'
    provider_only: true
  - field: 'name'
  - field: 'update_time'
