resource: 'google_logging_folder_bucket_config'
generation_type: 'handwritten'
api_service_name: 'logging.googleapis.com'
api_version: 'v2'
api_resource_type_kind: 'LogBucket'
api_variant_patterns:
  - 'folders/{folder}/locations/{location}/buckets/{bucket}'
fields:
  - field: 'bucket_id'
  - api_field: 'cmekSettings.kmsKeyName'
  - api_field: 'cmekSettings.kmsKeyVersionName'
  - api_field: 'cmekSettings.name'
  - api_field: 'cmekSettings.serviceAccountId'
  - api_field: 'description'
  - field: 'folder'
  - api_field: 'indexConfigs.fieldPath'
  - api_field: 'indexConfigs.type'
  - api_field: 'lifecycleState'
  - field: 'location'
  - api_field: 'name'
  - api_field: 'retentionDays'
