# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_logging_folder_settings'
generation_type: 'mmv1'
source_file: 'products/logging/FolderSettings.yaml'
api_service_name: 'logging.googleapis.com'
api_version: 'v2'
api_resource_type_kind: 'Settings'
api_variant_patterns:
  - 'folders/{folder}/settings'
fields:
  - field: 'disable_default_sink'
  - field: 'folder'
    provider_only: true
  - field: 'kms_key_name'
  - field: 'kms_service_account_id'
  - field: 'logging_service_account_id'
  - field: 'name'
  - field: 'storage_location'
