resource: 'google_logging_folder_bucket_config'
generation_type: 'handwritten'
api_service_name: 'logging.googleapis.com'
api_version: 'v2'
api_resource_type_kind: 'LogBucket'
fields:
  - field: 'bucket_id'
  - field: 'cmek_settings.kms_key_name'
  - field: 'cmek_settings.kms_key_version_name'
  - field: 'cmek_settings.name'
  - field: 'cmek_settings.service_account_id'
  - field: 'description'
  - field: 'folder'
  - field: 'index_configs.field_path'
  - field: 'index_configs.type'
  - field: 'lifecycle_state'
  - field: 'location'
  - field: 'name'
  - field: 'retention_days'
