// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/biglakehive/HiveDatabase.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/iam_policy.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package biglakehive

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/hashicorp/errwrap"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"google.golang.org/api/cloudresourcemanager/v1"

	"github.com/hashicorp/terraform-provider-google/google/registry"
	"github.com/hashicorp/terraform-provider-google/google/tpgiamresource"
	"github.com/hashicorp/terraform-provider-google/google/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google/google/transport"
)

var (
	_ = regexp.Match
	_ = strings.Trim
	_ = errwrap.Wrap
	_ = schema.Noop
)

func init() {
	registry.Schema{
		Name:        "google_biglake_hive_database_iam_binding",
		ProductName: "BiglakeHive",
		Type:        registry.SchemaTypeIAMResource,
		Schema:      tpgiamresource.ResourceIamBinding(BiglakeHiveHiveDatabaseIamSchema, BiglakeHiveHiveDatabaseIamUpdaterProducer, BiglakeHiveHiveDatabaseIdParseFunc),
	}.Register()
	registry.Schema{
		Name:        "google_biglake_hive_database_iam_member",
		ProductName: "BiglakeHive",
		Type:        registry.SchemaTypeIAMResource,
		Schema:      NewBiglakeHiveHiveDatabaseIamMemberResource(),
	}.Register()
	registry.Schema{
		Name:        "google_biglake_hive_database_iam_policy",
		ProductName: "BiglakeHive",
		Type:        registry.SchemaTypeIAMResource,
		Schema:      tpgiamresource.ResourceIamPolicy(BiglakeHiveHiveDatabaseIamSchema, BiglakeHiveHiveDatabaseIamUpdaterProducer, BiglakeHiveHiveDatabaseIdParseFunc),
	}.Register()
	registry.Schema{
		Name:        "google_biglake_hive_database_iam_policy",
		ProductName: "BiglakeHive",
		Type:        registry.SchemaTypeIAMDataSource,
		Schema:      tpgiamresource.DataSourceIamPolicy(BiglakeHiveHiveDatabaseIamSchema, BiglakeHiveHiveDatabaseIamUpdaterProducer),
	}.Register()
}

// NewBiglakeHiveHiveDatabaseIamMemberResource returns the google_biglake_hive_database_iam_member
// managed resource. It is shared by the managed resource registration and the
// list resource, so both stay in sync.
func NewBiglakeHiveHiveDatabaseIamMemberResource() *schema.Resource {
	return tpgiamresource.ResourceIamMember(
		BiglakeHiveHiveDatabaseIamSchema,
		BiglakeHiveHiveDatabaseIamUpdaterProducer,
		BiglakeHiveHiveDatabaseIdParseFunc,
		tpgiamresource.IamWithParentResourceIdentity(BiglakeHiveHiveDatabaseIamParentParentResourceIdentityParser),
	)
}

var BiglakeHiveHiveDatabaseIamSchema = map[string]*schema.Schema{
	"project": {
		Type:     schema.TypeString,
		Computed: true,
		Optional: true,
		ForceNew: true,
	},
	"catalog": {
		Type:     schema.TypeString,
		Required: true,
		ForceNew: true,
	},
	"name": {
		Type:             schema.TypeString,
		Required:         true,
		ForceNew:         true,
		DiffSuppressFunc: tpgresource.CompareSelfLinkOrResourceName,
	},
}

type BiglakeHiveHiveDatabaseIamUpdater struct {
	project string
	catalog string
	name    string
	d       tpgresource.TerraformResourceData
	Config  *transport_tpg.Config
}

func BiglakeHiveHiveDatabaseIamUpdaterProducer(d tpgresource.TerraformResourceData, config *transport_tpg.Config) (tpgiamresource.ResourceIamUpdater, error) {
	values := make(map[string]string)

	project, _ := tpgresource.GetProject(d, config)
	if project != "" {
		if err := d.Set("project", project); err != nil {
			return nil, fmt.Errorf("Error setting project: %s", err)
		}
	}
	values["project"] = project
	if v, ok := d.GetOk("catalog"); ok {
		values["catalog"] = v.(string)
	}

	if v, ok := d.GetOk("name"); ok {
		values["name"] = v.(string)
	}

	// We may have gotten either a long or short name, so attempt to parse long name if possible
	m, err := tpgresource.GetImportIdQualifiers([]string{"projects/(?P<project>[^/]+)/catalogs/(?P<catalog>[^/]+)/namespaces/(?P<name>[^/]+)", "(?P<project>[^/]+)/(?P<catalog>[^/]+)/(?P<name>[^/]+)", "(?P<catalog>[^/]+)/(?P<name>[^/]+)", "(?P<name>[^/]+)"}, d, config, d.Get("name").(string))
	if err != nil {
		return nil, err
	}

	for k, v := range m {
		values[k] = v
	}

	u := &BiglakeHiveHiveDatabaseIamUpdater{
		project: values["project"],
		catalog: values["catalog"],
		name:    values["name"],
		d:       d,
		Config:  config,
	}

	if err := d.Set("project", u.project); err != nil {
		return nil, fmt.Errorf("Error setting project: %s", err)
	}
	if err := d.Set("catalog", u.catalog); err != nil {
		return nil, fmt.Errorf("Error setting catalog: %s", err)
	}
	if err := d.Set("name", u.GetResourceId()); err != nil {
		return nil, fmt.Errorf("Error setting name: %s", err)
	}

	return u, nil
}

func BiglakeHiveHiveDatabaseIdParseFunc(d *schema.ResourceData, config *transport_tpg.Config) error {
	values := make(map[string]string)

	project, _ := tpgresource.GetProject(d, config)
	if project != "" {
		values["project"] = project
	}

	m, err := tpgresource.GetImportIdQualifiers([]string{"projects/(?P<project>[^/]+)/catalogs/(?P<catalog>[^/]+)/namespaces/(?P<name>[^/]+)", "(?P<project>[^/]+)/(?P<catalog>[^/]+)/(?P<name>[^/]+)", "(?P<catalog>[^/]+)/(?P<name>[^/]+)", "(?P<name>[^/]+)"}, d, config, d.Id())
	if err != nil {
		return err
	}

	for k, v := range m {
		values[k] = v
	}

	u := &BiglakeHiveHiveDatabaseIamUpdater{
		project: values["project"],
		catalog: values["catalog"],
		name:    values["name"],
		d:       d,
		Config:  config,
	}
	if err := d.Set("name", u.GetResourceId()); err != nil {
		return fmt.Errorf("Error setting name: %s", err)
	}
	d.SetId(u.GetResourceId())
	return nil
}

func (u *BiglakeHiveHiveDatabaseIamUpdater) GetResourceIamPolicy() (*cloudresourcemanager.Policy, error) {
	url, err := u.qualifyHiveDatabaseUrl("getIamPolicy")
	if err != nil {
		return nil, err
	}

	project, err := tpgresource.GetProject(u.d, u.Config)
	if err != nil {
		return nil, err
	}
	var obj map[string]interface{}

	userAgent, err := tpgresource.GenerateUserAgentString(u.d, u.Config.UserAgent)
	if err != nil {
		return nil, err
	}

	policy, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    u.Config,
		Method:    "GET",
		Project:   project,
		RawURL:    url,
		UserAgent: userAgent,
		Body:      obj,
	})
	if err != nil {
		return nil, fmt.Errorf("Error retrieving IAM policy for %s: %w", u.DescribeResource(), err)
	}

	out := &cloudresourcemanager.Policy{}
	err = tpgresource.Convert(policy, out)
	if err != nil {
		return nil, fmt.Errorf("Cannot convert a policy to a resource manager policy: %w", err)
	}

	return out, nil
}

func (u *BiglakeHiveHiveDatabaseIamUpdater) SetResourceIamPolicy(policy *cloudresourcemanager.Policy) error {
	json, err := tpgresource.ConvertToMap(policy)
	if err != nil {
		return err
	}

	obj := make(map[string]interface{})
	obj["policy"] = json

	url, err := u.qualifyHiveDatabaseUrl("setIamPolicy")
	if err != nil {
		return err
	}
	project, err := tpgresource.GetProject(u.d, u.Config)
	if err != nil {
		return err
	}

	userAgent, err := tpgresource.GenerateUserAgentString(u.d, u.Config.UserAgent)
	if err != nil {
		return err
	}

	_, err = transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    u.Config,
		Method:    "POST",
		Project:   project,
		RawURL:    url,
		UserAgent: userAgent,
		Body:      obj,
		Timeout:   u.d.Timeout(schema.TimeoutCreate),
	})
	if err != nil {
		return fmt.Errorf("Error setting IAM policy for %s: %w", u.DescribeResource(), err)
	}

	return nil
}

func (u *BiglakeHiveHiveDatabaseIamUpdater) qualifyHiveDatabaseUrl(methodIdentifier string) (string, error) {
	urlTemplate := fmt.Sprintf("{{BiglakeHiveBasePath}}%s:%s", fmt.Sprintf("v1/projects/%s/catalogs/%s/namespaces/%s", u.project, u.catalog, u.name), methodIdentifier)
	url, err := tpgresource.ReplaceVars(u.d, u.Config, urlTemplate)
	if err != nil {
		return "", err
	}
	return url, nil
}

func (u *BiglakeHiveHiveDatabaseIamUpdater) GetResourceId() string {
	return fmt.Sprintf("v1/projects/%s/catalogs/%s/namespaces/%s", u.project, u.catalog, u.name)
}

func BiglakeHiveHiveDatabaseIamParentParentResourceIdentityParser(d *schema.ResourceData, identity *schema.IdentityData, transportConfig *transport_tpg.Config) (string, error) {
	return tpgiamresource.ParseIamResourceIdentity(d, identity, transportConfig, tpgiamresource.IamResourceIdentityConfig{
		Params: []tpgiamresource.IamIdentityParam{
			{Key: "project", IdentityKey: "project"},
			{Key: "catalog", IdentityKey: "catalog"},
			{Key: "name", IdentityKey: "name"},
		},
		UriFormat: "v1/projects/%s/catalogs/%s/namespaces/%s",
	})
}

func (u *BiglakeHiveHiveDatabaseIamUpdater) GetMutexKey() string {
	return fmt.Sprintf("iam-biglakehive-hivedatabase-%s", u.GetResourceId())
}

func (u *BiglakeHiveHiveDatabaseIamUpdater) DescribeResource() string {
	return fmt.Sprintf("biglakehive hivedatabase %q", u.GetResourceId())
}
