// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package spanner_test

import (
	"fmt"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"github.com/hashicorp/terraform-provider-google/google/acctest"
	"github.com/hashicorp/terraform-provider-google/google/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google/google/transport"
)

func TestAccSpannerInstanceConfig_spannerInstanceConfigBasicExample(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"instance_config_name": "custom-tf-test-nam11-config",
		"random_suffix":        acctest.RandString(t, 10),
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		CheckDestroy:             testAccCheckSpannerInstanceConfigDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccSpannerInstanceConfig_spannerInstanceConfigBasicExample(context),
			},
			{
				ResourceName:            "google_spanner_instance_config.example",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"labels", "terraform_labels"},
			},
		},
	})
}

func testAccSpannerInstanceConfig_spannerInstanceConfigBasicExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_spanner_instance_config" "example" {
  name          = "%{instance_config_name}"
  display_name  = "Test Spanner Instance Config"
  base_config    = "nam11"
  replicas     {
      location = "us-west1"
      type = "READ_ONLY"
      default_leader_location = false
 }
 labels = {
    "foo" = "bar"
  }
}
`, context)
}

func testAccCheckSpannerInstanceConfigDestroyProducer(t *testing.T) func(s *terraform.State) error {
	return func(s *terraform.State) error {
		for name, rs := range s.RootModule().Resources {
			if rs.Type != "google_spanner_instance_config" {
				continue
			}
			if strings.HasPrefix(name, "data.") {
				continue
			}

			config := acctest.GoogleProviderConfig(t)

			url, err := tpgresource.ReplaceVarsForTest(config, rs, "{{SpannerBasePath}}projects/{{project}}/instanceConfigs/{{name}}")
			if err != nil {
				return err
			}

			billingProject := ""

			if config.BillingProject != "" {
				billingProject = config.BillingProject
			}

			_, err = transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
				Config:    config,
				Method:    "GET",
				Project:   billingProject,
				RawURL:    url,
				UserAgent: config.UserAgent,
			})
			if err == nil {
				return fmt.Errorf("SpannerInstanceConfig still exists at %s", url)
			}
		}

		return nil
	}
}
