# Copyright IBM Corp. 2014, 2026
# SPDX-License-Identifier: MPL-2.0
resource: google_access_context_manager_service_perimeter_ingress_policy
generation_type: mmv1
source_file: products/accesscontextmanager/ServicePerimeterIngressPolicy.yaml
api_service_name: accesscontextmanager.googleapis.com
api_version: v1
api_resource_type_kind: ServicePerimeter
fields:
    - field: access_policy_id
      provider_only: true
    - api_field: status.ingressPolicies.etag
      field: etag
    - api_field: status.ingressPolicies.ingressFrom.identities
      field: ingress_from.identities
    - api_field: status.ingressPolicies.ingressFrom.identityType
      field: ingress_from.identity_type
    - api_field: status.ingressPolicies.ingressFrom.sources.accessLevel
      field: ingress_from.sources.access_level
    - api_field: status.ingressPolicies.ingressFrom.sources.resource
      field: ingress_from.sources.resource
    - api_field: status.ingressPolicies.ingressTo.operations.methodSelectors.method
      field: ingress_to.operations.method_selectors.method
    - api_field: status.ingressPolicies.ingressTo.operations.methodSelectors.permission
      field: ingress_to.operations.method_selectors.permission
    - api_field: status.ingressPolicies.ingressTo.operations.serviceName
      field: ingress_to.operations.service_name
    - api_field: status.ingressPolicies.ingressTo.resources
      field: ingress_to.resources
    - api_field: status.ingressPolicies.ingressTo.roles
      field: ingress_to.roles
    - field: perimeter
      provider_only: true
    - api_field: status.ingressPolicies.title
      field: title
    - field: deletion_policy
      provider_only: true
