// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

// Package iap contains resources, datasources, etc. for the identity-aware proxy service.
package iap

import (
	"github.com/hashicorp/terraform-provider-google/google/registry"
)

const ProductName = "iap"

func init() {
	registry.Product{
		Name:    "iap",
		BaseUrl: "https://iap.googleapis.com/v1/",
	}.Register()
}
