# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_iap_settings'
generation_type: 'mmv1'
source_file: 'products/iap/Settings.yaml'
api_service_name: 'iap.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'Settings'
fields:
  - field: 'access_settings.allowed_domains_settings.domains'
  - field: 'access_settings.allowed_domains_settings.enable'
  - field: 'access_settings.cors_settings.allow_http_options'
  - field: 'access_settings.gcip_settings.login_page_uri'
  - field: 'access_settings.gcip_settings.tenant_ids'
  - field: 'access_settings.identity_sources'
  - field: 'access_settings.oauth_settings.login_hint'
  - field: 'access_settings.oauth_settings.programmatic_clients'
  - field: 'access_settings.reauth_settings.max_age'
  - field: 'access_settings.reauth_settings.method'
  - field: 'access_settings.reauth_settings.policy_type'
  - field: 'access_settings.workforce_identity_settings.oauth2.client_id'
  - field: 'access_settings.workforce_identity_settings.oauth2.client_secret'
  - field: 'access_settings.workforce_identity_settings.oauth2.client_secret_sha256'
  - field: 'access_settings.workforce_identity_settings.workforce_pools'
  - field: 'application_settings.access_denied_page_settings.access_denied_page_uri'
  - field: 'application_settings.access_denied_page_settings.generate_troubleshooting_uri'
  - field: 'application_settings.access_denied_page_settings.remediation_token_generation_enabled'
  - field: 'application_settings.attribute_propagation_settings.enable'
  - field: 'application_settings.attribute_propagation_settings.expression'
  - field: 'application_settings.attribute_propagation_settings.output_credentials'
  - field: 'application_settings.cookie_domain'
  - field: 'application_settings.csm_settings.rctoken_aud'
  - field: 'name'
