resource: 'google_project_access_approval_settings'
generation_type: 'mmv1'
source_file: 'products/accessapproval/ProjectSettings.yaml'
api_service_name: 'accessapproval.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'AccessApprovalSettings'
api_variant_patterns:
  - 'projects/{project}/accessApprovalSettings'
fields:
  - api_field: 'activeKeyVersion'
  - api_field: 'ancestorHasActiveKeyVersion'
  - api_field: 'enrolledAncestor'
  - api_field: 'enrolledServices.cloudProduct'
  - api_field: 'enrolledServices.enrollmentLevel'
  - api_field: 'invalidKeyVersion'
  - api_field: 'name'
  - api_field: 'notificationEmails'
  - api_field: 'project'
  - field: 'project_id'
    provider_only: true
