# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_project_access_approval_settings'
generation_type: 'mmv1'
source_file: 'products/accessapproval/ProjectSettings.yaml'
api_service_name: 'accessapproval.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'AccessApprovalSettings'
api_variant_patterns:
  - 'projects/{project}/accessApprovalSettings'
fields:
  - field: 'active_key_version'
  - field: 'ancestor_has_active_key_version'
  - field: 'enrolled_ancestor'
  - field: 'enrolled_services.cloud_product'
  - field: 'enrolled_services.enrollment_level'
  - field: 'invalid_key_version'
  - field: 'name'
  - field: 'notification_emails'
  - field: 'project'
  - field: 'project_id'
    provider_only: true
