// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

// Package pubsublite contains resources, datasources, etc. for the cloud pub/sub service.
package pubsublite

import (
	"github.com/hashicorp/terraform-provider-google/google/registry"
)

const ProductName = "pubsublite"

func init() {
	registry.Product{
		Name:    "pubsublite",
		BaseUrl: "https://{{region}}-pubsublite.googleapis.com/v1/admin/",
	}.Register()
}
