# Copyright IBM Corp. 2014, 2026
# SPDX-License-Identifier: MPL-2.0
resource: google_compute_network_peering_routes_config
generation_type: mmv1
source_file: products/compute/NetworkPeeringRoutesConfig.yaml
api_service_name: compute.googleapis.com
api_version: v1
api_resource_type_kind: Network
fields:
    - api_field: peerings.exportCustomRoutes
      field: export_custom_routes
    - api_field: peerings.exportSubnetRoutesWithPublicIp
      field: export_subnet_routes_with_public_ip
    - api_field: peerings.importCustomRoutes
      field: import_custom_routes
    - api_field: peerings.importSubnetRoutesWithPublicIp
      field: import_subnet_routes_with_public_ip
    - field: network
      provider_only: true
    - api_field: peerings.name
      field: peering
