# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_identity_platform_config'
generation_type: 'mmv1'
source_file: 'products/identityplatform/Config.yaml'
api_service_name: 'identitytoolkit.googleapis.com'
api_version: 'v2'
api_resource_type_kind: 'Config'
fields:
  - field: 'authorized_domains'
  - field: 'autodelete_anonymous_users'
  - field: 'blocking_functions.forward_inbound_credentials.access_token'
  - field: 'blocking_functions.forward_inbound_credentials.id_token'
  - field: 'blocking_functions.forward_inbound_credentials.refresh_token'
  - field: 'blocking_functions.triggers.triggers.function_uri'
  - field: 'blocking_functions.triggers.triggers.update_time'
  - field: 'client.api_key'
  - field: 'client.firebase_subdomain'
  - field: 'client.permissions.disabled_user_deletion'
  - field: 'client.permissions.disabled_user_signup'
  - field: 'mfa.enabled_providers'
  - field: 'mfa.provider_configs.state'
  - field: 'mfa.provider_configs.totp_provider_config.adjacent_intervals'
  - field: 'mfa.state'
  - field: 'monitoring.request_logging.enabled'
  - field: 'multi_tenant.allow_tenants'
  - field: 'multi_tenant.default_tenant_location'
  - field: 'name'
  - field: 'quota.sign_up_quota_config.quota'
  - field: 'quota.sign_up_quota_config.quota_duration'
  - field: 'quota.sign_up_quota_config.start_time'
  - field: 'sign_in.allow_duplicate_emails'
  - field: 'sign_in.anonymous.enabled'
  - field: 'sign_in.email.enabled'
  - field: 'sign_in.email.password_required'
  - field: 'sign_in.hash_config.algorithm'
  - field: 'sign_in.hash_config.memory_cost'
  - field: 'sign_in.hash_config.rounds'
  - field: 'sign_in.hash_config.salt_separator'
  - field: 'sign_in.hash_config.signer_key'
  - field: 'sign_in.phone_number.enabled'
  - field: 'sign_in.phone_number.test_phone_numbers'
  - field: 'sms_region_config.allow_by_default.disallowed_regions'
  - field: 'sms_region_config.allowlist_only.allowed_regions'
