resource: 'google_identity_platform_tenant_inbound_saml_config'
generation_type: 'mmv1'
api_service_name: 'identitytoolkit.googleapis.com'
api_version: 'v2'
api_resource_type_kind: 'InboundSamlConfig'
