swagger: '2.0'
info:
  title: dev 
  description: Sample API on API Gateway with a Cloud Run backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /hello:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
        address: https://google.com
      responses:
        '200':
          description: A successful response
          schema:
            type: string