// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

// Package cloudbuild contains resources, datasources, etc. for the cloud build service.
package cloudbuild

import (
	"github.com/hashicorp/terraform-provider-google/google/registry"
)

const ProductName = "cloudbuild"

func init() {
	registry.Product{
		Name:    "cloudbuild",
		BaseUrl: "https://cloudbuild.googleapis.com/v1/",
	}.Register()
}
