# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_integrations_auth_config'
generation_type: 'mmv1'
source_file: 'products/integrations/AuthConfig.yaml'
api_service_name: 'integrations.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'AuthConfig'
api_variant_patterns:
  - 'projects/{project}/locations/{location}/authConfigs/{authConfig}'
fields:
  - field: 'certificate_id'
  - field: 'client_certificate.encrypted_private_key'
  - field: 'client_certificate.passphrase'
  - field: 'client_certificate.ssl_certificate'
  - field: 'create_time'
  - field: 'creator_email'
  - field: 'credential_type'
  - field: 'decrypted_credential.auth_token.token'
  - field: 'decrypted_credential.auth_token.type'
  - field: 'decrypted_credential.credential_type'
  - field: 'decrypted_credential.jwt.jwt'
  - field: 'decrypted_credential.jwt.jwt_header'
  - field: 'decrypted_credential.jwt.jwt_payload'
  - field: 'decrypted_credential.jwt.secret'
  - field: 'decrypted_credential.oauth2_authorization_code.auth_endpoint'
  - field: 'decrypted_credential.oauth2_authorization_code.client_id'
  - field: 'decrypted_credential.oauth2_authorization_code.client_secret'
  - field: 'decrypted_credential.oauth2_authorization_code.scope'
  - field: 'decrypted_credential.oauth2_authorization_code.token_endpoint'
  - field: 'decrypted_credential.oauth2_client_credentials.client_id'
  - field: 'decrypted_credential.oauth2_client_credentials.client_secret'
  - field: 'decrypted_credential.oauth2_client_credentials.request_type'
  - field: 'decrypted_credential.oauth2_client_credentials.scope'
  - field: 'decrypted_credential.oauth2_client_credentials.token_endpoint'
  - field: 'decrypted_credential.oauth2_client_credentials.token_params.entries.key.literal_value.string_value'
  - field: 'decrypted_credential.oauth2_client_credentials.token_params.entries.value.literal_value.string_value'
  - field: 'decrypted_credential.oidc_token.audience'
  - field: 'decrypted_credential.oidc_token.service_account_email'
  - field: 'decrypted_credential.oidc_token.token'
  - field: 'decrypted_credential.oidc_token.token_expire_time'
  - field: 'decrypted_credential.service_account_credentials.scope'
  - field: 'decrypted_credential.service_account_credentials.service_account'
  - field: 'decrypted_credential.username_and_password.password'
  - field: 'decrypted_credential.username_and_password.username'
  - field: 'description'
  - field: 'display_name'
  - field: 'encrypted_credential'
  - field: 'expiry_notification_duration'
  - field: 'last_modifier_email'
  - field: 'location'
    provider_only: true
  - field: 'name'
  - field: 'override_valid_time'
  - field: 'reason'
  - field: 'state'
  - field: 'update_time'
  - field: 'valid_time'
  - field: 'visibility'
