resource: 'google_cloudbuildv2_connection'
generation_type: 'mmv1'
source_file: 'products/cloudbuildv2/Connection.yaml'
api_service_name: 'cloudbuild.googleapis.com'
api_version: 'v2'
api_resource_type_kind: 'Connection'
fields:
  - api_field: 'annotations'
  - api_field: 'bitbucketCloudConfig.authorizerCredential.userTokenSecretVersion'
  - api_field: 'bitbucketCloudConfig.authorizerCredential.username'
  - api_field: 'bitbucketCloudConfig.readAuthorizerCredential.userTokenSecretVersion'
  - api_field: 'bitbucketCloudConfig.readAuthorizerCredential.username'
  - api_field: 'bitbucketCloudConfig.webhookSecretSecretVersion'
  - api_field: 'bitbucketCloudConfig.workspace'
  - api_field: 'bitbucketDataCenterConfig.authorizerCredential.userTokenSecretVersion'
  - api_field: 'bitbucketDataCenterConfig.authorizerCredential.username'
  - api_field: 'bitbucketDataCenterConfig.hostUri'
  - api_field: 'bitbucketDataCenterConfig.readAuthorizerCredential.userTokenSecretVersion'
  - api_field: 'bitbucketDataCenterConfig.readAuthorizerCredential.username'
  - api_field: 'bitbucketDataCenterConfig.serverVersion'
  - api_field: 'bitbucketDataCenterConfig.serviceDirectoryConfig.service'
  - api_field: 'bitbucketDataCenterConfig.sslCa'
  - api_field: 'bitbucketDataCenterConfig.webhookSecretSecretVersion'
  - api_field: 'createTime'
  - api_field: 'disabled'
  - field: 'effective_annotations'
    provider_only: true
  - api_field: 'etag'
  - api_field: 'githubConfig.appInstallationId'
  - api_field: 'githubConfig.authorizerCredential.oauthTokenSecretVersion'
  - api_field: 'githubConfig.authorizerCredential.username'
  - api_field: 'githubEnterpriseConfig.appId'
  - api_field: 'githubEnterpriseConfig.appInstallationId'
  - api_field: 'githubEnterpriseConfig.appSlug'
  - api_field: 'githubEnterpriseConfig.hostUri'
  - api_field: 'githubEnterpriseConfig.privateKeySecretVersion'
  - api_field: 'githubEnterpriseConfig.serviceDirectoryConfig.service'
  - api_field: 'githubEnterpriseConfig.sslCa'
  - api_field: 'githubEnterpriseConfig.webhookSecretSecretVersion'
  - api_field: 'gitlabConfig.authorizerCredential.userTokenSecretVersion'
  - api_field: 'gitlabConfig.authorizerCredential.username'
  - api_field: 'gitlabConfig.hostUri'
  - api_field: 'gitlabConfig.readAuthorizerCredential.userTokenSecretVersion'
  - api_field: 'gitlabConfig.readAuthorizerCredential.username'
  - api_field: 'gitlabConfig.serverVersion'
  - api_field: 'gitlabConfig.serviceDirectoryConfig.service'
  - api_field: 'gitlabConfig.sslCa'
  - api_field: 'gitlabConfig.webhookSecretSecretVersion'
  - api_field: 'installationState.actionUri'
  - api_field: 'installationState.message'
  - api_field: 'installationState.stage'
  - field: 'location'
    provider_only: true
  - field: 'name'
    provider_only: true
  - api_field: 'reconciling'
  - api_field: 'updateTime'
