# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_dataproc_gdc_application_environment'
generation_type: 'mmv1'
source_file: 'products/dataprocgdc/ApplicationEnvironment.yaml'
api_service_name: 'dataprocgdc.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'ApplicationEnvironment'
autogen_status: true
fields:
  - field: 'annotations'
  - field: 'application_environment_id'
    provider_only: true
  - field: 'create_time'
  - field: 'display_name'
  - field: 'effective_annotations'
    provider_only: true
  - field: 'effective_labels'
    provider_only: true
  - field: 'labels'
  - field: 'location'
    provider_only: true
  - field: 'name'
  - field: 'namespace'
  - field: 'serviceinstance'
    provider_only: true
  - field: 'spark_application_environment_config.default_properties'
  - field: 'spark_application_environment_config.default_version'
  - field: 'terraform_labels'
    provider_only: true
  - field: 'uid'
  - field: 'update_time'
