resource: 'google_dataproc_gdc_application_environment'
generation_type: 'mmv1'
source_file: 'products/dataprocgdc/ApplicationEnvironment.yaml'
api_service_name: 'dataprocgdc.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'ApplicationEnvironment'
autogen_status: true
fields:
  - api_field: 'annotations'
  - field: 'application_environment_id'
    provider_only: true
  - api_field: 'createTime'
  - api_field: 'displayName'
  - field: 'effective_annotations'
    provider_only: true
  - field: 'effective_labels'
    provider_only: true
  - api_field: 'labels'
  - field: 'location'
    provider_only: true
  - api_field: 'name'
  - api_field: 'namespace'
  - field: 'serviceinstance'
    provider_only: true
  - api_field: 'sparkApplicationEnvironmentConfig.defaultProperties'
  - api_field: 'sparkApplicationEnvironmentConfig.defaultVersion'
  - field: 'terraform_labels'
    provider_only: true
  - api_field: 'uid'
  - api_field: 'updateTime'
