# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_dialogflow_cx_security_settings'
generation_type: 'mmv1'
source_file: 'products/dialogflowcx/SecuritySettings.yaml'
api_service_name: 'dialogflow.googleapis.com'
api_version: 'v3'
api_resource_type_kind: 'SecuritySettings'
fields:
  - field: 'audio_export_settings.audio_export_pattern'
  - field: 'audio_export_settings.audio_format'
  - field: 'audio_export_settings.enable_audio_redaction'
  - field: 'audio_export_settings.gcs_bucket'
  - field: 'deidentify_template'
  - field: 'display_name'
  - field: 'insights_export_settings.enable_insights_export'
  - field: 'inspect_template'
  - field: 'location'
    provider_only: true
  - field: 'name'
  - field: 'purge_data_types'
  - field: 'redaction_scope'
  - field: 'redaction_strategy'
  - field: 'retention_strategy'
  - field: 'retention_window_days'
