# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_dialogflow_cx_environment'
generation_type: 'mmv1'
source_file: 'products/dialogflowcx/Environment.yaml'
api_service_name: 'dialogflow.googleapis.com'
api_version: 'v3'
api_resource_type_kind: 'Environment'
fields:
  - field: 'description'
  - field: 'display_name'
  - field: 'name'
  - field: 'parent'
    provider_only: true
  - field: 'update_time'
  - field: 'version_configs.version'
