# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_dialogflow_cx_generative_settings'
generation_type: 'mmv1'
source_file: 'products/dialogflowcx/GenerativeSettings.yaml'
api_service_name: 'dialogflow.googleapis.com'
api_version: 'v3'
api_resource_type_kind: 'GenerativeSettings'
fields:
  - field: 'fallback_settings.prompt_templates.display_name'
  - field: 'fallback_settings.prompt_templates.frozen'
  - field: 'fallback_settings.prompt_templates.prompt_text'
  - field: 'fallback_settings.selected_prompt'
  - field: 'generative_safety_settings.banned_phrases.language_code'
  - field: 'generative_safety_settings.banned_phrases.text'
  - field: 'generative_safety_settings.default_banned_phrase_match_strategy'
  - field: 'knowledge_connector_settings.agent'
  - field: 'knowledge_connector_settings.agent_identity'
  - field: 'knowledge_connector_settings.agent_scope'
  - field: 'knowledge_connector_settings.business'
  - field: 'knowledge_connector_settings.business_description'
  - field: 'knowledge_connector_settings.disable_data_store_fallback'
  - field: 'language_code'
  - field: 'llm_model_settings.model'
  - field: 'llm_model_settings.prompt_text'
  - field: 'name'
  - field: 'parent'
    provider_only: true
