resource: 'google_dialogflow_cx_playbook'
generation_type: 'mmv1'
source_file: 'products/dialogflowcx/Playbook.yaml'
api_service_name: 'dialogflow.googleapis.com'
api_version: 'v3'
api_resource_type_kind: 'Playbook'
fields:
  - field: 'create_time'
  - field: 'display_name'
  - field: 'goal'
  - field: 'instruction.guidelines'
  - field: 'instruction.steps.steps'
    json: true
  - field: 'instruction.steps.text'
  - field: 'llm_model_settings.model'
  - field: 'llm_model_settings.prompt_text'
  - field: 'name'
  - field: 'parent'
    provider_only: true
  - field: 'playbook_type'
  - field: 'referenced_flows'
  - field: 'referenced_playbooks'
  - field: 'referenced_tools'
  - field: 'token_count'
  - field: 'update_time'
