name: ensure-service-team-labels

permissions: 
  issues: write 

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:
  workflow_call:
 
jobs:
  modify-labels:
    if: github.repository == 'GoogleCloudPlatform/magic-modules' ||  github.repository == 'hashicorp/terraform-provider-google'
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: GoogleCloudPlatform/magic-modules
      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: '^1.23.0'
      - name: Build issue-labeler
        run: |
          cd tools/issue-labeler
          go build
      - name: Run issue-labeler
        run: |
          cd tools/issue-labeler
          ./issue-labeler setup-labels ${{  github.repository  }}
