name: Issue Comment Created Triage

on:
  issue_comment:
    types: [created]

jobs:
  remove_waiting_response:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: actions-ecosystem/action-remove-labels@556e306654eb4c343ecaff657772edaa3f1add86
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          labels: waiting-response
