name: "Pull Request Reviewer"
on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]

permissions:
  pull-requests: write

jobs:
  add-reviewer:
    if: ${{ github.actor != 'modular-magician' }}
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@0a2c53d3721e4c5cfcce6afd4014aecc337979f6 # v2.0.2
        with:
          configuration-path: ".github/reviewer-lottery.yml"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

