name: Service Labeler

on:
  issues:
    types: [opened, edited, unlabeled]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Checkout magic modules
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        repository: GoogleCloudPlatform/magic-modules
        ref: main
        path: magic-modules
    - name: Setup go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version: '>=1.19.0'
    - name: Check for service labels
      id: service_labels
      run: |
        serviceLabels="$(echo '${{ toJson(github.event.issue.labels.*.name) }}' | jq -c 'map(select(startswith("service/")))')"
        echo "Service labels: $serviceLabels"
        echo "service_labels=$serviceLabels" >> $GITHUB_OUTPUT
    - name: Build issue-labeler binary
      run: |
        cd magic-modules/tools/issue-labeler
        go build .
    - name: Compute new labels
      id: compute_new_labels
      if: ${{ steps.service_labels.outputs.service_labels == '[]' }}
      env:
        ISSUE_BODY: ${{ github.event.issue.body }}
      run: |
        cd magic-modules/tools/issue-labeler
        labels=$(./issue-labeler compute-new-labels)
        echo "Labels: $labels"
        echo "labels=$labels" >> $GITHUB_OUTPUT
    - name: Apply labels
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      if: ${{ steps.service_labels.outputs.service_labels == '[]' && steps.compute_new_labels.outputs.labels != '' }}
      with:
        script: |
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ${{ steps.compute_new_labels.outputs.labels }}
          })
