name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '10 3 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@98ed4cb500039dbcccf4bd9bedada4d0187f2757
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 9999
          days-before-close: 90
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          close-issue-message: |
            I'm going to close this issue due to inactivity (_90 days_ without response ⏳ ). This helps our maintainers find and focus on the active issues.

            If this issue was automatically closed and you feel this issue should be reopened, we encourage creating a new issue linking back to this one for added context. Thank you!

          close-pr-message: |
            I'm going to close this pull requests due to inactivity (_90 days_ without response ⏳ ). This helps our maintainers find and focus on the active contributions.

            If this pull request was automatically closed and you feel this pull request should be reopened, we encourage creating a new pull request linking back to this one for added context. Thank you!
